export type UserRole = 'buyer' | 'lister' | 'admin'
export type ListingStatus = 'draft' | 'pending' | 'published' | 'rejected' | 'archived'
export type ListingCategory = 'sale' | 'rent'
export type PropertyType =
  | 'condo'
  | 'house_lot'
  | 'townhouse'
  | 'lot'
  | 'commercial'
  | 'apartment'
  | 'bedspace'
export type InquiryStatus = 'new' | 'replied' | 'closed'
export type ReportStatus = 'open' | 'reviewed' | 'actioned'
export type ReportReason = 'scam' | 'wrong_info' | 'duplicate' | 'inappropriate' | 'other'
